### PR TITLE
fix: fixed serving matching urls to be strict, not loose

### LINKED ISSUE #3: Expected lambda file not found
I cannot reach any routes deeper than `/`.

Here's my now.json routes section:
```
"routes": [
  { "src": "/", "dest": "/services/index.js" },
  { "src": "/locations", "methods": ["GET"], "dest": "/services/locations/read.js" },
  { "src": "/users", "methods": ["GET"], "dest": "/services/users/read.js" },
  { "src": "/users/(?<id>[^/]*)", "methods": ["GET"], "dest": "/services/users/read.js?id=$id" },
  { "src": "/users", "methods": ["POST"], "dest": "/services/users/create.js" }
]
```

If I try to reach /locations, I get the error `Expected lambda file not found`. Deployed on Now 2.0, this works, so there is a problem with the `now-we-test` server reaching the .js files specified in the routes.

### PR DESCRIPTION
**Pull request by lucasconstantino**
Fixes #3

### CODE REVIEW

**Comment by lucasconstantino** [comment]
@josephxanderson do you mind to give this a try?

**Comment by ghost** [comment]
Thank you. @lucasconstantino was this properly pushed to NPM? I have updated but I'm still getting the same error. I'm on the latest: `0.4.0`

**Comment by lucasconstantino** [comment]
@josephxanderson this is odd... I've refactoring the src matching to be strict, and added some tests to ensure this is working. Please, have a look at the tests (more precisely the [now.json](https://github.com/lucasconstantino/now-we-test/blob/master/tests/sample-project/now.json) of the sample testing project) and see if you find anything different than your scenario ;)

**Comment by jeremyrajan** [comment]
Has this been fixed? I still see the issue :/

**Pull request merged**
